// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/company/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/company/[id]').default>>>>
    }
    '/api/company': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/company/index').default>>>>
    }
    '/api/departments/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/departments/[id]').default>>>>
    }
    '/api/departments': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/departments/index').default>>>>
    }
    '/api/leave_request': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leave_request/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leave_request/index.post').default>>>>
    }
    '/api/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login.post').default>>>>
    }
    '/api/salary': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/salary/index.post').default>>>>
    }
    '/api/staff/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/staff/[id]').default>>>>
    }
    '/api/staff': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/staff/index').default>>>>
    }
    '/api/stafflogin/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stafflogin/login.post').default>>>>
    }
    '/api/stafflogin/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stafflogin/profile.get').default>>>>
    }
    '/api/update-profile': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/update-profile.post').default>>>>
    }
    '/api/upload': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}