// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/17/2026, 11:51:41 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/xampp/htdocs/staff-admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/staff-admin/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/staff-admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/staff-admin/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/staff-admin/plugins/**/*.{js,ts,mjs}","C:/xampp/htdocs/staff-admin/composables/**/*.{js,ts,mjs}","C:/xampp/htdocs/staff-admin/utils/**/*.{js,ts,mjs}","C:/xampp/htdocs/staff-admin/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/staff-admin/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/staff-admin/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/staff-admin/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;