// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 15/4/2026, 4:39:23 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/xampp--workingnow/htdocs/Welfog_Data/STAFF_ADMIN/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp--workingnow/htdocs/Welfog_Data/STAFF_ADMIN/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp--workingnow/htdocs/Welfog_Data/STAFF_ADMIN/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp--workingnow/htdocs/Welfog_Data/STAFF_ADMIN/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp--workingnow/htdocs/Welfog_Data/STAFF_ADMIN/plugins/**/*.{js,ts,mjs}","C:/xampp--workingnow/htdocs/Welfog_Data/STAFF_ADMIN/composables/**/*.{js,ts,mjs}","C:/xampp--workingnow/htdocs/Welfog_Data/STAFF_ADMIN/utils/**/*.{js,ts,mjs}","C:/xampp--workingnow/htdocs/Welfog_Data/STAFF_ADMIN/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp--workingnow/htdocs/Welfog_Data/STAFF_ADMIN/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/xampp--workingnow/htdocs/Welfog_Data/STAFF_ADMIN/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/xampp--workingnow/htdocs/Welfog_Data/STAFF_ADMIN/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;